<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>fel.cvut</groupId>
    <artifactId>JAVA_TLS_TEST</artifactId>
    <version>1.0-SNAPSHOT</version>

    <packaging>jar</packaging>
    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.wolfssl</groupId>
            <artifactId>wolfssljni</artifactId>
            <version>1.0.0-PQC</version>
        </dependency>
        <dependency>
            <artifactId>ratis-server</artifactId>
            <groupId>org.apache.ratis</groupId>
            <version>3.2.2</version>
        </dependency>
        <dependency>
            <artifactId>ratis-grpc</artifactId>
            <groupId>org.apache.ratis</groupId>
            <version>3.2.2</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>

            <!-- Compiler -->
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>

            <!-- Run main class -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <configuration>
                    <mainClass>fel.cvut.PQCHybridServer</mainClass>
                </configuration>
            </plugin>

        </plugins>
    </build>

</project>